#SPDX-License-Identifier: BSD-3-Clause
galaxy_info:
  author: Bruno Thomsen
  description: Install CLI monitoring tools for a host.

  issue_tracker_url: https://github.com/baxeno/home-router/issues

  license: BSD-3-Clause

  min_ansible_version: 2.1

  platforms:
  - name: Fedora
    versions:
    - all

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
