#SPDX-License-Identifier: Apache-2.0
---
# meta file for os-requirements

galaxy_info:
  author: Bruno Thomsen
  description: Check OS requirements and install required Ansible dependencies

  issue_tracker_url: https://github.com/baxeno/home-router/issues

  license: Apache-2.0

  min_ansible_version: "2.16"

  platforms:
    - name: "Fedora"
      versions:
        - "41"
        - "42"
        - "43"
        - "44"
    - name: "AlmaLinux"
      versions:
        - "10"
    - name: "CentOS"
      versions:
        - "10"

  galaxy_tags: []

dependencies: []
