#SPDX-License-Identifier: Apache-2.0
---
all:
  children:
    routers:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ansible_playbook_python}}"

          # Required configuration parameters
          router_wan_interface: ""
          router_lan_interface: ""

          # SSH public key for local on-prem management
          router_admin_public_key: ""

          # Optional configuration parameters can be found here:
          # soho-router/defaults/main.yml
