# SPDX-License-Identifier: Apache-2.0
---
all:
  children:
    routers:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ansible_playbook_python}}"

          # Tuxedo Nano Pro - Gen12 (AMD Ryzen 5 7535U)
          # Realtek RTL8125 2.5GbE
          router_wan_interface: "enp1s0"
          # Realtek RTL8111/8168/8211/8411
          router_lan_interface: "enp2s0f0"

          router_hostname: "tuxedo"
          router_domain: "tux.internal"

          router_admin_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINIQVLQKS/yN8XMspNw+JsVbfmDUa7y9L0T/zzr4tv4V"

          router_lan_network: "192.168.82.82/24"

          # DNS4EU For Public - Protective Resolution
          dhcp_primary_dns: "86.54.11.1"
          dhcp_secondary_dns: "86.54.11.201"

          dhcp_client_pool_start: "192.168.82.100"
          dhcp_client_pool_end: "192.168.82.199"

          dhcp_client_reservations:
            # Multiroom streaming - Bedroom
            # WiFi: "90:56:82:b0:74:45", Ethernet: "90:56:82:b0:74:44"
            - name: "bluesound-pulse-m"
              mac: "90:56:82:b0:74:45"
              ipv4: "192.168.82.50"
            # Multiroom streaming - Bathroom
            # WiFi: "e8:5c:5f:48:7a:db", Ethernet: "90:56:82:62:28:23"
            - name: "bluesound-pulse-flex-2i"
              mac: "e8:5c:5f:48:7a:db"
              ipv4: "192.168.82.51"
            # Multiroom streaming - Living room - Stereo speakers (LR, front)
            # WiFi: "90:56:82:83:07:37", Ethernet: "90:56:82:83:07:36"
            - name: "bluesound-power-node-n331"
              mac: "90:56:82:83:07:37"
              ipv4: "192.168.82.52"
            # Multiroom streaming - Living room - Left surround speaker (LS, back)
            # WiFi: "90:56:82:b0:a8:11", Ethernet: "90:56:82:b0:a8:10"
            - name: "bluesound-pulse-m-ls"
              mac: "90:56:82:b0:a8:11"
              ipv4: "192.168.82.53"
            # Multiroom streaming - Living room - Right surround speaker (RS, back)
            # WiFi: "90:56:82:b0:a4:2b", Ethernet: "90:56:82:b0:a4:2a"
            - name: "bluesound-pulse-m-rs"
              mac: "90:56:82:b0:a4:2b"
              ipv4: "192.168.82.54"
