---
# tasks file for home-router

- name: Install packages on router
  become: yes
  ansible.builtin.dnf:
    name: dnf-automatic
    state: present
  when: ansible_distribution == 'Fedora' and ansible_distribution_version|int <= 40

- name: Install packages on router
  become: yes
  ansible.builtin.dnf:
    name: dnf5-plugin-automatic, libcurl-full
    allowerasing: true
    state: present
  when: ansible_distribution == 'Fedora' and ansible_distribution_version|int >= 41

- name: Enable automatic updates on router
  ansible.builtin.systemd_service:
    name: dnf-automatic-install.timer
    enabled: true
    state: started
  when: ansible_distribution == 'Fedora' and ansible_distribution_version|int <= 40

- name: Directory for dnf-automatic-install.timer override
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/system/dnf-automatic-install.timer.d
    owner: root
    group: root
    state: directory
    mode: '0755'
  when: ansible_distribution == 'Fedora' and ansible_distribution_version|int <= 40

- name: Enable weekly auto updates of router
  become: yes
  ansible.builtin.copy:
    src: files/dnf-override.conf
    dest: /etc/systemd/system/dnf-automatic-install.timer.d/dnf-override.conf
    owner: root
    group: root
    mode: '0440'
  when: ansible_distribution == 'Fedora' and ansible_distribution_version|int <= 40

- name: Reboot router after updates if needed
  ansible.builtin.lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: '^reboot = '
    line: 'reboot = when-changed'
  when: ansible_distribution == 'Fedora' and ansible_distribution_version|int <= 40

