#SPDX-License-Identifier: Apache-2.0
---
# tasks file for os-requirements

- name: Unsupported distributions and operating system
  fail:
    msg: "Use Fedora Server for latest hardware support and AlmaLinux for LTS on supported hardware"
  when: (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'RedHat') or
        (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'Fedora' and ansible_facts['distribution_major_version']|int <= 34) or
        (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version']|int <= 9) or
        (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version']|int <= 9) or
        (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'Scientific') or
        (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'CloudLinux') or
        (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'OracleLinux') or
        (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'Amazon') or
        (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'XenServer') or
        (ansible_facts['os_family'] == 'Debian') or
        (ansible_facts['os_family'] == 'Suse') or
        (ansible_facts['os_family'] == 'Gentoo') or
        (ansible_facts['os_family'] == 'Archlinux') or
        (ansible_facts['os_family'] == 'Mandrake') or
        (ansible_facts['os_family'] == 'HP-UX') or
        (ansible_facts['os_family'] == 'AIX') or
        (ansible_facts['os_family'] == 'Solaris') or
        (ansible_facts['os_family'] == 'FreeBSD') or
        (ansible_facts['os_family'] == 'Darwin') or
        (ansible_facts['os_family'] == 'Windows')

- name: Supported Linux distribution has reached End-of-Life (EoL)
  fail:
    msg: "Warning: Use newer version of Fedora Server"
  when: (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'Fedora' and ansible_facts['distribution_major_version']|int <= 41)
  ignore_errors: True

# -----------------------------------------------------------------------------
# Install needed Ansible collections
# -----------------------------------------------------------------------------
- name: Enable EPEL Repository on AlmaLinux OS and CentOS Stream
  become: true
  ansible.builtin.dnf:
    name: epel-release
    state: present
  when: (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_release'] == 'Stream') or
        (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == 'AlmaLinux')

- name: Install Ansible collection (Community) for NetworkManager configuration
  become: true
  ansible.builtin.dnf:
    name: ansible-collection-community-general
    state: present

- name: Install Ansible collection (POSIX platforms) for firewalld configuration
  become: true
  ansible.builtin.dnf:
    name: ansible-collection-ansible-posix, python3-firewall
    state: present

- name: Install Ansible Utilities collection dependency (Python library netaddr) for management and manipulation of configuration data
  become: true
  ansible.builtin.dnf:
    name: python3-netaddr
    state: present
