#SPDX-License-Identifier: Apache-2.0
---
# meta file for soho-router

galaxy_info:
  author: Bruno Thomsen
  description: Setup router based on Linux, systemd, Kea DHCP, NetworkManager and firewalld.

  issue_tracker_url: https://github.com/baxeno/home-router/issues

  license: Apache-2.0

  min_ansible_version: "2.16"

  platforms:
    - name: "Fedora"
      versions:
        - "41"
        - "42"
        - "43"
        - "44"
    - name: "AlmaLinux"
      versions:
        - "10"
    - name: "CentOS"
      versions:
        - "10"

  galaxy_tags: []

dependencies:
  - role: os-requirements
