#SPDX-License-Identifier: Apache-2.0
---
- hosts: routers
  tasks:
    - name: Bootstrap host requirements and check OS requirements
      ansible.builtin.include_role:
        name: os-requirements

- hosts: routers
  tasks:
    - name: Setup router
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop:
        - auto-update
        - soho-router
      loop_control:
        loop_var: role
