#SPDX-License-Identifier: Apache-2.0
---
# Bootstrap soho-router role host requirements and validate OS requirements
- hosts: routers
  gather_facts: true
  roles:
    - os-requirements

- hosts: routers
  gather_facts: true
  roles:
    - auto-update
    - soho-router
