# SPDX-License-Identifier: Apache-2.0
---
- name: Run home-router | os_requirements
  hosts: routers
  tasks:
    - name: Bootstrap host requirements and check OS requirements
      ansible.builtin.include_role:
        name: os_requirements

- name: Run home-router | auto_update and soho_router
  hosts: routers
  tasks:
    - name: Setup router
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop:
        - auto_update
        - soho_router
      loop_control:
        loop_var: role
