# SPDX-License-Identifier: Apache-2.0
---
# handlers file for os_requirements

- name: New collections installed
  ansible.builtin.fail:
    msg: "Ansible collections installed; rerun playbook to continue."
