name: Ansible lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ansible-lint:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install ansible-lint
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible-lint

      - name: Ansible lint
        run: |
          ansible-lint --profile=production --offline ansible/
