name: Shellcheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shellcheck:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Shellcheck
        run: |
          find . -type f -name '*.sh' -print -exec shellcheck -x -- {} \;
